### ISSUE TITLE
Make "Active data legends" window larger

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MassGIS/morisoliver#11]
```
What steps will reproduce the problem?
Several users have commented that they did not initially notice the legend for 
the active data layers. If the "Active data legends" window were larger, then 
it would be more noticeable.  A suggestion is to have the "Available data 
layers" window be 30% of the height, the "Active data layers" window be 30%, 
and the "Active data legends" window be 40%.

What version of the product are you using? On what operating system?
Tested MORIS v. 0.35 on Windows 7 and Firefox 3.16.13.


```

Original issue reported on code.google.com by `emily.hu...@state.ma.us` on 18 Feb 2011 at 6:53

Attachments:
* [initial_view.jpg](https://storage.googleapis.com/google-code-attachments/morisoliver/issue-11/comment-0/initial_view.jpg)
* [suggested_initial_view.jpg](https://storage.googleapis.com/google-code-attachments/morisoliver/issue-11/comment-0/suggested_initial_view.jpg)

**Comment by MassGIS** [comment]
Close for now
