### ISSUE TITLE
Replace spaces with underscores in exported ZIP file names

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MassGIS/morisoliver#214]
```
What steps will reproduce the problem?
If users includes a space in the ZIP file name during the final step of the 
data export wizard, they'll get an error when they click the blue "here" to 
download the data.

What is the expected output? What do you see instead?
The script that builds the ZIP file should replace any spaces in the file name 
with an underscore.
```

Original issue reported on code.google.com by `emily.hu...@state.ma.us` on 26 Apr 2013 at 8:10

**Comment by MassGIS** [comment]
Aleda 11/12/2015 Still an issue in FF 42, IE 11 and Chrome 46.  If I ask for "test 2.zip" it creates test.zip but the user tries to download test 2.zip.  The back end machine maps.massgis.state.ma.us is a Linux server so spaces are awkward, let's avoid them.

**Comment by MassGIS** [comment]
I like the solution - I am no longer allowed to type a space.
