### ISSUE TITLE
Clear button does not delete map pin from MassGIS ArcGIS Server geocoding

### ISSUE THREAD

**Issue by MassGIS** [MassGIS/morisoliver#246]
We’ve switched to ArcGIS Server geocoding in OLIVER
http://maps.massgis.state.ma.us/map_ol/oliver.php 
![red_map_pin_screenshot](https://cloud.githubusercontent.com/assets/10077576/11127939/e32f6898-8944-11e5-871a-74dca84a112a.png)
The tool uses this MassGIS ArcGIS Server geocoding service: 
http://maps.massgis.state.ma.us/cgi-bin/proxy.cgi?url=http://gisprpxy.itd.state.ma.us/MassGISGeocodeServiceApplication/MassGISCustomGeocodeService.asmx

The geocoding works fine.

But the "clear location search results from map" button 
![clear_location_search_results_button](https://cloud.githubusercontent.com/assets/10077576/11127963/052f8b12-8945-11e5-8b1d-46b78653fd95.png)
doesn’t delete the map pin 

![map_pin_after_arcgis_server_geocode_screentshot](https://cloud.githubusercontent.com/assets/10077576/11127981/1ef58cfe-8945-11e5-8a3c-1d73e8814c45.png)

after the geocode.
There is one error in the console:
![clear_map_pin_after_arcgis_server_geocoding_console_error](https://cloud.githubusercontent.com/assets/10077576/11128028/4d9baa7a-8945-11e5-8698-0a4df4ea4f13.png)

If another geocode is done, the pin in replaced.  (So at least they don’t pile up on the map).

Is there a way to tweak the code so that the “clear location search results from map” clears the blue map pin? 

Note – we are not yet using the Google geocoding code, as we don’t have a key at this point.

**Comment by MassGIS** [comment]
Aleda 11/12/2015 Still an issue in FF 42, IE 11 and Chrome 46.
We've gotten a lot of user complaint about this actually.

**Comment by cgalvarino** [comment]
@MassGIS, I see the URL for this new service but not the required parameter(s).  Could you send a full example?

**Comment by MassGIS** [comment]
Works in http://maps.massgis.state.ma.us/map_ol_2016/oliver.php
