### ISSUE TITLE
Support consumption of WMTS (Web Map Tile Service) 

### ISSUE THREAD

**Issue by MassGIS** [MassGIS/morisoliver#250]
Aleda 11/12/2015 - Would need to have a sample to work with.

**Comment by cgalvarino** [comment]
@MassGIS, I'm going through issues to see if there are any blockers.  You identified one . . . could you find a sample data source?  And I have to remind myself how the wheels work . . . a new layer like this has to go into a folderset.xml.  Does it also have to end up in OL_MORIS_cache land?

**Comment by MassGIS** [comment]
I'm getting an error when I add Google WMTS from the folder, but then I switch the basemap to "Create custom basemap".  I think it should throw up the yellow ! and not draw Google until the basemap comes back to a 900913 flavor one.  Instead, it kind of freezes.
![error_when_wmts_folder_switch_to_create_custom_basemap](https://cloud.githubusercontent.com/assets/10077576/15374280/6b16119c-1d17-11e6-90f6-56e0374e1fed.PNG)

**Comment by cgalvarino** [comment]
Roger that.  Not an easy one to fix.  Thanks for finding it.

At least it throws up the yellow bang . . . and then some.

**Comment by MassGIS** [comment]
I still only can zoom down to level 15 with the Google basemap... although I applied the new code and I see the new line in http://maps.massgis.state.ma.us/map_ol_2016/js/map.js

**Comment by MassGIS** [comment]
BTW I am using Firefox and I cleared my cache and closed and opened the browser...

**Comment by cgalvarino** [comment]
Huh. Somehow one of the later merges undid it.
