### ISSUE TITLE
Remove 3 calls to Bing services

### ISSUE THREAD

**Issue by MassGIS** [MassGIS/morisoliver#254]
There are 3 requests to Bing for info on the basemaps.
However, MassGIS OLIVER launches are so numerous that we exceed the terms of service. 
We removed the Bing basemaps before because of AGOL tile line up issues.
These 3 requests are being denied, so we might as well comment out (instead of delete) the calls to Bing metadata (in case we want to bring them back sometime). 
![bing_metadata_gets](https://cloud.githubusercontent.com/assets/10077576/12860255/7306723c-cc29-11e5-84b8-34f310c8f96c.PNG)

**Comment by cgalvarino** [comment]
@MassGIS, where are you seeing this error?  I visited production OLIVER and don't see it.

**Comment by MassGIS** [comment]
When I open http://maps.massgis.state.ma.us/map_ol/oliver.php in Firefox and use Firebug I see the 3 requests:
![oliver_3_bing_requests](https://cloud.githubusercontent.com/assets/10077576/14718126/ca62365e-07c2-11e6-9bf3-b422acdcfde8.PNG)

**Comment by cgalvarino** [comment]
Ah, thanks, @MassGIS.  I misread this issue thinking I was looking for errors, not valid responses.  Got it!

**Comment by MassGIS** [comment]
This is fixed in my test area http://maps.massgis.state.ma.us/map_ol_2016/oliver.php
